version: '3'
services:
  # Add this top-level entry
  redis:
    image: redis
    container_name: cache
    expose:
      - 6379

  "web_application":
    build: "./web_application"
    ports:
      - "3000:8080"
      - "9229:9229"
    volumes:
        - "./web_application/src:/web_application/src"
    depends_on:
      - database
    # some definitions
    links:
      - redis
    environment:
      - REDIS_URL=redis://cache
        # rest of the environment definitions
  database:
    build: ./database
    ports:
      - "3306:3306"
    environment:
        - MYSQL_ROOT_PASSWORD=FredricJoakim
        - MYSQL_DATABASE=meetandeat_db
  nginx:
    build: ./SPA
    ports:
      - "3001:80"
    depends_on:
      - web_application
